/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { GroupMemberListRelationFilter } from "../../groupMember/base/GroupMemberListRelationFilter";
import { GroupChatListRelationFilter } from "../../groupChat/base/GroupChatListRelationFilter";
import { GroupCallListRelationFilter } from "../../groupCall/base/GroupCallListRelationFilter";

@InputType()
class GroupWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  createdBy?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => GroupMemberListRelationFilter,
  })
  @ValidateNested()
  @Type(() => GroupMemberListRelationFilter)
  @IsOptional()
  @Field(() => GroupMemberListRelationFilter, {
    nullable: true,
  })
  groupMembers?: GroupMemberListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => GroupChatListRelationFilter,
  })
  @ValidateNested()
  @Type(() => GroupChatListRelationFilter)
  @IsOptional()
  @Field(() => GroupChatListRelationFilter, {
    nullable: true,
  })
  groupChats?: GroupChatListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => GroupCallListRelationFilter,
  })
  @ValidateNested()
  @Type(() => GroupCallListRelationFilter)
  @IsOptional()
  @Field(() => GroupCallListRelationFilter, {
    nullable: true,
  })
  groupCalls?: GroupCallListRelationFilter;
}

export { GroupWhereInput as GroupWhereInput };
