/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { GroupMemberUpdateManyWithoutGroupsInput } from "./GroupMemberUpdateManyWithoutGroupsInput";
import { Type } from "class-transformer";
import { GroupChatUpdateManyWithoutGroupsInput } from "./GroupChatUpdateManyWithoutGroupsInput";
import { GroupCallUpdateManyWithoutGroupsInput } from "./GroupCallUpdateManyWithoutGroupsInput";

@InputType()
class GroupUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  createdBy?: string | null;

  @ApiProperty({
    required: false,
    type: () => GroupMemberUpdateManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => GroupMemberUpdateManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => GroupMemberUpdateManyWithoutGroupsInput, {
    nullable: true,
  })
  groupMembers?: GroupMemberUpdateManyWithoutGroupsInput;

  @ApiProperty({
    required: false,
    type: () => GroupChatUpdateManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => GroupChatUpdateManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => GroupChatUpdateManyWithoutGroupsInput, {
    nullable: true,
  })
  groupChats?: GroupChatUpdateManyWithoutGroupsInput;

  @ApiProperty({
    required: false,
    type: () => GroupCallUpdateManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => GroupCallUpdateManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => GroupCallUpdateManyWithoutGroupsInput, {
    nullable: true,
  })
  groupCalls?: GroupCallUpdateManyWithoutGroupsInput;
}

export { GroupUpdateInput as GroupUpdateInput };
