/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { GroupMemberCreateNestedManyWithoutGroupsInput } from "./GroupMemberCreateNestedManyWithoutGroupsInput";
import { Type } from "class-transformer";
import { GroupChatCreateNestedManyWithoutGroupsInput } from "./GroupChatCreateNestedManyWithoutGroupsInput";
import { GroupCallCreateNestedManyWithoutGroupsInput } from "./GroupCallCreateNestedManyWithoutGroupsInput";

@InputType()
class GroupCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  createdBy?: string | null;

  @ApiProperty({
    required: false,
    type: () => GroupMemberCreateNestedManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => GroupMemberCreateNestedManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => GroupMemberCreateNestedManyWithoutGroupsInput, {
    nullable: true,
  })
  groupMembers?: GroupMemberCreateNestedManyWithoutGroupsInput;

  @ApiProperty({
    required: false,
    type: () => GroupChatCreateNestedManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => GroupChatCreateNestedManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => GroupChatCreateNestedManyWithoutGroupsInput, {
    nullable: true,
  })
  groupChats?: GroupChatCreateNestedManyWithoutGroupsInput;

  @ApiProperty({
    required: false,
    type: () => GroupCallCreateNestedManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => GroupCallCreateNestedManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => GroupCallCreateNestedManyWithoutGroupsInput, {
    nullable: true,
  })
  groupCalls?: GroupCallCreateNestedManyWithoutGroupsInput;
}

export { GroupCreateInput as GroupCreateInput };
