/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { GroupMember } from "./GroupMember";
import { GroupMemberCountArgs } from "./GroupMemberCountArgs";
import { GroupMemberFindManyArgs } from "./GroupMemberFindManyArgs";
import { GroupMemberFindUniqueArgs } from "./GroupMemberFindUniqueArgs";
import { CreateGroupMemberArgs } from "./CreateGroupMemberArgs";
import { UpdateGroupMemberArgs } from "./UpdateGroupMemberArgs";
import { DeleteGroupMemberArgs } from "./DeleteGroupMemberArgs";
import { Group } from "../../group/base/Group";
import { User } from "../../user/base/User";
import { GroupMemberService } from "../groupMember.service";
@graphql.Resolver(() => GroupMember)
export class GroupMemberResolverBase {
  constructor(protected readonly service: GroupMemberService) {}

  async _groupMembersMeta(
    @graphql.Args() args: GroupMemberCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [GroupMember])
  async groupMembers(
    @graphql.Args() args: GroupMemberFindManyArgs
  ): Promise<GroupMember[]> {
    return this.service.groupMembers(args);
  }

  @graphql.Query(() => GroupMember, { nullable: true })
  async groupMember(
    @graphql.Args() args: GroupMemberFindUniqueArgs
  ): Promise<GroupMember | null> {
    const result = await this.service.groupMember(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => GroupMember)
  async createGroupMember(
    @graphql.Args() args: CreateGroupMemberArgs
  ): Promise<GroupMember> {
    return await this.service.createGroupMember({
      ...args,
      data: {
        ...args.data,

        group: args.data.group
          ? {
              connect: args.data.group,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => GroupMember)
  async updateGroupMember(
    @graphql.Args() args: UpdateGroupMemberArgs
  ): Promise<GroupMember | null> {
    try {
      return await this.service.updateGroupMember({
        ...args,
        data: {
          ...args.data,

          group: args.data.group
            ? {
                connect: args.data.group,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => GroupMember)
  async deleteGroupMember(
    @graphql.Args() args: DeleteGroupMemberArgs
  ): Promise<GroupMember | null> {
    try {
      return await this.service.deleteGroupMember(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Group, {
    nullable: true,
    name: "group",
  })
  async getGroup(@graphql.Parent() parent: GroupMember): Promise<Group | null> {
    const result = await this.service.getGroup(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: GroupMember): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
